"""add razorpay fields to settlements

Revision ID: c5bd442a3026
Revises: 53164b27f050
Create Date: 2026-06-28 17:53:42.394650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5bd442a3026'
down_revision: Union[str, Sequence[str], None] = '53164b27f050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlements', sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
    op.add_column('settlements', sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlements', 'razorpay_payment_id')
    op.drop_column('settlements', 'razorpay_order_id')
    # ### end Alembic commands ###
